name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rust:1.88.0-slim
    steps:
      - uses: actions/checkout@v4
      - name: Build dynamic library
        run: cargo build --release
      - name: Run tests
        run: cargo test --release
